name: MyLocalTon (TON master)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Java 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Java Projects
        run: |
          mvn clean compile package -DskipTests

      - name: Build and push
        id: docker_build_1
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./
          no-cache: true
          file: ./Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:v4.0.0

      - name: Build and push faucet
        id: docker_build_2
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./
          file: ./faucet/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-faucet:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-faucet:v4.0.0

      - name: Build and push data
        id: docker_build_3
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./
          file: ./data/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-data:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-data:v4.0.0

      - name: Build and push blockchain-explorer
        id: docker_build_4
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./
          file: ./explorer/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-explorer:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-explorer:v4.0.0

      - name: Build and push time-machine
        id: docker_build_5
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./
          file: ./time-machine/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-time-machine:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-time-machine:v4.0.0

      - name: Build and push lite-server
        id: docker_build_6
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./
          file: ./lite-server/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-lite-server:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-lite-server:v4.0.0